version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "installing nodejs"
  pre_build:
    commands:
      - printenv
      - echo "we are in the pre build phase"
  build:
    commands:
      - echo "we are in the build block"
      - echo "running test ...."
      - grep -Fq "cloud" index.html
  post_build:
    commands:
      - echo "we are in the post build phase"

artifacts:
  files:
    - '**/*'
  name: aws_devops_poc_mywebb_artifacts


